from src.preprocessing.config import INPUT_FOLDER_PATH, OUTPUT_PERSISTENCE_PATH, SAMPLE_FOLDER_PATH
from src.preprocessing.preprocessor import preprocess_collection

preprocess_collection(SAMPLE_FOLDER_PATH, OUTPUT_PERSISTENCE_PATH)
