from src.preprocessing.config import INPUT_FOLDER_PATH, OUTPUT_PERSISTENCE_PATH
from src.preprocessing.preprocessor import preprocess_collection

preprocess_collection(INPUT_FOLDER_PATH, OUTPUT_PERSISTENCE_PATH)
